on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: abhisheaacr.azurecr.io
        username: ${{ secrets.acr_abhisheaAcr_username }}
        password: ${{ secrets.acr_abhisheaAcr_password }}
    
    - run: |
        docker build . -t abhisheaacr.azurecr.io/bugbash16228d0e:${{ github.sha }}
        docker push abhisheaacr.azurecr.io/bugbash16228d0e:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_bugbash162-2_kubeConfig }}
      id: login
    
    - name: create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep bugbash162246dd | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace bugbash162246dd`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: bugbash162246dd
        container-registry-url: abhisheaacr.azurecr.io
        container-registry-username: ${{ secrets.acr_abhisheaAcr_username }}
        container-registry-password: ${{ secrets.acr_abhisheaAcr_password }}
        secret-name: bugbash1622dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: bugbash162246dd
        manifests: |
          manifests/deployment-4.yml
          manifests/service-4.yml
        images: |
          abhisheaacr.azurecr.io/bugbash16228d0e:${{ github.sha }}
        imagepullsecrets: |
          bugbash1622dockerauth