on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: abhisheaacr.azurecr.io
        username: ${{ secrets.acr_abhisheaacr_username }}
        password: ${{ secrets.acr_abhisheaacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Application" -f  "Application/Dockerfile" -t abhisheaacr.azurecr.io/bugbash1621:${{ github.sha }}
        docker push abhisheaacr.azurecr.io/bugbash1621:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_bugbash1621_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep bugbash1621e1eb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace bugbash1621e1eb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: bugbash1621e1eb
        container-registry-url: abhisheaacr.azurecr.io
        container-registry-username: ${{ secrets.acr_abhisheaacr_username }}
        container-registry-password: ${{ secrets.acr_abhisheaacr_password }}
        secret-name: bugbash1621dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: bugbash1621e1eb
        manifests: |
          manifests/deployment-5.yml
          manifests/service-5.yml
        images: |
          abhisheaacr.azurecr.io/bugbash1621:${{ github.sha }}
        imagepullsecrets: |
          bugbash1621dockerauth
