on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: anuragdevopsaksacr.azurecr.io
        username: ${{ secrets.acr_anuragDevOpsaksacr_username }}
        password: ${{ secrets.acr_anuragDevOpsaksacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Application" -f  "Application/Dockerfile" -t anuragdevopsaksacr.azurecr.io/bugbash16223832:${{ github.sha }}
        docker push anuragdevopsaksacr.azurecr.io/bugbash16223832:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_bugbash162_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep bugbash16222607 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace bugbash16222607`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: bugbash16222607
        container-registry-url: anuragdevopsaksacr.azurecr.io
        container-registry-username: ${{ secrets.acr_anuragDevOpsaksacr_username }}
        container-registry-password: ${{ secrets.acr_anuragDevOpsaksacr_password }}
        secret-name: bugbash1622dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: bugbash16222607
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          anuragdevopsaksacr.azurecr.io/bugbash16223832:${{ github.sha }}
        imagepullsecrets: |
          bugbash1622dockerauth
